// Code generated by protoc-gen-go. DO NOT EDIT.
// source: studentservice.proto

package studentservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetStudentRequest struct {
	StudentId            int32    `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudentRequest) Reset()         { *m = GetStudentRequest{} }
func (m *GetStudentRequest) String() string { return proto.CompactTextString(m) }
func (*GetStudentRequest) ProtoMessage()    {}
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86c9bf4783b504bd, []int{0}
}

func (m *GetStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentRequest.Unmarshal(m, b)
}
func (m *GetStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentRequest.Marshal(b, m, deterministic)
}
func (m *GetStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentRequest.Merge(m, src)
}
func (m *GetStudentRequest) XXX_Size() int {
	return xxx_messageInfo_GetStudentRequest.Size(m)
}
func (m *GetStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentRequest proto.InternalMessageInfo

func (m *GetStudentRequest) GetStudentId() int32 {
	if m != nil {
		return m.StudentId
	}
	return 0
}

type StudentData struct {
	StudentId            int32    `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentFirstName     string   `protobuf:"bytes,2,opt,name=student_first_name,json=studentFirstName,proto3" json:"student_first_name,omitempty"`
	StudentSecondName    string   `protobuf:"bytes,3,opt,name=student_second_name,json=studentSecondName,proto3" json:"student_second_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentData) Reset()         { *m = StudentData{} }
func (m *StudentData) String() string { return proto.CompactTextString(m) }
func (*StudentData) ProtoMessage()    {}
func (*StudentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_86c9bf4783b504bd, []int{1}
}

func (m *StudentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentData.Unmarshal(m, b)
}
func (m *StudentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentData.Marshal(b, m, deterministic)
}
func (m *StudentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentData.Merge(m, src)
}
func (m *StudentData) XXX_Size() int {
	return xxx_messageInfo_StudentData.Size(m)
}
func (m *StudentData) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentData.DiscardUnknown(m)
}

var xxx_messageInfo_StudentData proto.InternalMessageInfo

func (m *StudentData) GetStudentId() int32 {
	if m != nil {
		return m.StudentId
	}
	return 0
}

func (m *StudentData) GetStudentFirstName() string {
	if m != nil {
		return m.StudentFirstName
	}
	return ""
}

func (m *StudentData) GetStudentSecondName() string {
	if m != nil {
		return m.StudentSecondName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetStudentRequest)(nil), "studentservice.GetStudentRequest")
	proto.RegisterType((*StudentData)(nil), "studentservice.StudentData")
}

func init() { proto.RegisterFile("studentservice.proto", fileDescriptor_86c9bf4783b504bd) }

var fileDescriptor_86c9bf4783b504bd = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x15, 0x55, 0x32, 0xe2, 0x12, 0x74, 0x4f, 0x2d, 0x09, 0x86, 0x08, 0x06, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x72, 0x71, 0x41, 0x95, 0xc5, 0x67, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x71, 0x42, 0x45, 0x3c, 0x53, 0x94, 0xba, 0x18, 0xb9, 0xb8, 0xa1,
	0x3a, 0x5c, 0x12, 0x4b, 0x12, 0x09, 0x28, 0x17, 0xd2, 0xe1, 0x12, 0x82, 0x49, 0xa7, 0x65, 0x16,
	0x15, 0x97, 0xc4, 0xe7, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x09, 0x40,
	0x65, 0xdc, 0x40, 0x12, 0x7e, 0x89, 0xb9, 0xa9, 0x42, 0x7a, 0x5c, 0xc2, 0x30, 0xd5, 0xc5, 0xa9,
	0xc9, 0xf9, 0x79, 0x29, 0x10, 0xe5, 0xcc, 0x60, 0xe5, 0x82, 0x50, 0xa9, 0x60, 0xb0, 0x0c, 0x48,
	0xbd, 0x51, 0x1c, 0x17, 0x5f, 0x30, 0x4c, 0x10, 0xec, 0x25, 0x21, 0x1f, 0x2e, 0xae, 0x74, 0xb8,
	0x97, 0x84, 0x14, 0xf5, 0xd0, 0xc2, 0x01, 0xc3, 0xbb, 0x52, 0xd2, 0xe8, 0x4a, 0x90, 0x3c, 0x97,
	0xc4, 0x06, 0x0e, 0x37, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xd6, 0x08, 0x54, 0x4f,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentServiceClient interface {
	GetStudent(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*StudentData, error)
}

type studentServiceClient struct {
	cc *grpc.ClientConn
}

func NewStudentServiceClient(cc *grpc.ClientConn) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) GetStudent(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*StudentData, error) {
	out := new(StudentData)
	err := c.cc.Invoke(ctx, "/studentservice.StudentService/getStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServiceServer is the server API for StudentService service.
type StudentServiceServer interface {
	GetStudent(context.Context, *GetStudentRequest) (*StudentData, error)
}

// UnimplementedStudentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStudentServiceServer struct {
}

func (*UnimplementedStudentServiceServer) GetStudent(ctx context.Context, req *GetStudentRequest) (*StudentData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudent not implemented")
}

func RegisterStudentServiceServer(s *grpc.Server, srv StudentServiceServer) {
	s.RegisterService(&_StudentService_serviceDesc, srv)
}

func _StudentService_GetStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).GetStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/studentservice.StudentService/GetStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).GetStudent(ctx, req.(*GetStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StudentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "studentservice.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getStudent",
			Handler:    _StudentService_GetStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "studentservice.proto",
}
